---
version: '2.1'

services:
  div-pfe:
    env_file:
      - env_files/div-pfe.env
    ports:
      - 3000:3000

  div-rfe:
    env_file:
      - env_files/div-rfe.env
    ports:
      - 8084:3000

  div-dafe:
    env_file:
      - env_files/div-dafe.env
    ports:
      - 8085:3000

  div-dnfe:
    env_file:
      - env_files/div-dnfe.env
    ports:
      - 8086:3000

  redis:
    expose:
      - 6379

  fr-am:
    ports:
      - 8080:8080
      - 1389:1389

  fr-idm:
    ports:
      - 18080:18080
      - 9010:9010

  shared-db:
    ports:
      - 5432:5432

  smtp-server:
    ports:
      - 1025:1025
      - 8025:8025

  idam-api:
    ports:
      - 5000:5000
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - SPRING_PROFILES_ACTIVE=local
      - CACHING_ENABLED=false
      - SPRING_DATA_ELASTICSEARCH_PROPERTIES_PATH_HOME=/tmp/es
      - TESTING_SUPPORT_ENABLED=true
      - IDAMHEALTHCHECK_AM_ENABLED=false
      - IDAMHEALTHCHECK_IDM_ENABLED=false
      - STRATEGIC_ADMIN_URL=http://idam-web-admin:8082
      - STRATEGIC_WEBPUBLIC_URL=http://idam-web-public:9002
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-db:5432/openidm?currentSchema=fridam
      - SPRING_DATASOURCE_USERNAME=openidm
      - SPRING_DATASOURCE_PASSWORD=openidm
      - SECURITY_OAUTH2_CLIENT_CLIENTSECRET=password
      - SECURITY_OAUTH2_CLIENT_PRE_ESTABLISHED_REDIRECT_URI=http://idam-web-public:9002/login
      - SECURITY_OAUTH2_CLIENT_REGISTERED_REDIRECT_URI=http://idam-web-public:9002/login
      - IDAM_SPI_FORGEROCK_AM_ROOT=http://fr-am:8080/openam
      - IDAM_SPI_FORGEROCK_AM_TOPLEVELHOST=fr-am
      - IDAM_SPI_FORGEROCK_AM_USERNAME=amadmin
      - IDAM_SPI_FORGEROCK_AM_PASSWORD=Pa55word11
      - IDAM_SPI_FORGEROCK_AM_JWKSURIFOROAUTH2CLIENTS=http://fr-am:8080/openam/oauth2/hmcts/connect/jwk_uri
      - IDAM_SPI_FORGEROCK_IDM_ROOT=http://fr-idm:18080/openidm
      - IDAM_SPI_FORGEROCK_IDM_USERNAME=openidm-admin
      - IDAM_SPI_FORGEROCK_IDM_PASSWORD=openidm-admin
      - IDAM_SPI_FORGEROCK_IDM_PIN_DEFAULTPASSWORD=BlaBlaBlackSh33p

  idam-web-public:
    ports:
      - 9002:8080
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - STRATEGIC_SERVICE_URL=http://idam-api:5000

  idam-web-admin:
    ports:
      - 8082:8080
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - STRATEGIC_SERVICE_URL=http://idam-api:5000
      - STRATEGIC_PUBLIC_URL=http://idam-web-public:9002

  idam-importer:
    environment:
      - IDAM_API_URL=http://idam-api:5000
      - IDAM_ADMIN_USER=idamowner%40hmcts.net
      - IDAM_ADMIN_PASSWORD=Ref0rmIsFun
      - WAIT_HOSTS=idam-api:5000
      - WAIT_HOSTS_TIMEOUT=900

  div-cos:
    ports:
      - 4012:4012
    env_file:
      - env_files/div-cos.env

  div-cms:
    ports:
      - 4010:4010
    env_file:
      - env_files/div-cms.env

  div-fees-and-payments:
    ports:
      - 4009:4009

  div-evidence-management:
    environment:
      - IDAM_API_HEALTH_URI=http://idam-api:5000/health
      - IDAM_API_URL=http://idam-api:5000
      - AUTH_PROVIDER_SERVICE_CLIENT_BASEURL=http://service-auth-provider-api:8080
      - EVIDENCE_MANAGEMENT_UPLOAD_FILE_URL=http://div-evidence-management:9000/documents
      - EVIDENCE_MANAGEMENT_HEALTH_URL=http://div-evidence-management:9000//health
    ports:
      - 4006:4006

  div-payments-api:
    ports:
      - 4421:8080

  div-case-data-formatter:
    ports:
      - 4011:4011

  service-auth-provider-api:
    ports:
      - 4552:8080
    env_file:
      - env_files/service-auth-provider-api.env

  draft-store-api:
    ports:
      - 8800:8800

  shared-database:
    ports:
      - 5430:5432
    volumes:
      - shared-database-data:/var/lib/postgresql/data

  ccd-definition-store-api:
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - DEFINITION_STORE_DB_HOST=shared-database
      - DEFINITION_STORE_DB_PORT=5432
      - DEFINITION_STORE_DB_USERNAME=ccd_definition_store
      - DEFINITION_STORE_DB_PASSWORD=ccd_definition_store
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/ccd_definition_store
      - DEFINITION_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
      - DEFINITION_STORE_S2S_AUTHORISED_SERVICES=ccd_gateway,fpl_case_service
      - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
      - IDAM_USER_URL=http://idam-api:5000
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - REFORM_SERVICE_NAME=ccd-definition-store-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
      - APPINSIGHTS_INSTRUMENTATIONKEY=fake-key
      - ELASTIC_SEARCH_ENABLED=${ELASTIC_SEARCH_ENABLED:-false}
      - ELASTIC_SEARCH_HOST=ccd-elasticsearch
      - ELASTIC_SEARCH_FAIL_ON_IMPORT=true
#    env_file:
#      - env_files/ccd-definition-store-api.env
    ports:
      - 4451:4451

  ccd-data-store-api:
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - DATA_STORE_DB_HOST=shared-database
      - DATA_STORE_DB_PORT=5432
      - DATA_STORE_DB_USERNAME=ccd_data_store
      - DATA_STORE_DB_PASSWORD=ccd_data_store
      - DATA_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/ccd_data_store?stringtype=unspecified
      - DATA_STORE_TOKEN_SECRET=sdsadahjsadhgaskjhdhasghgkjasd
      - DATA_STORE_S2S_AUTHORISED_SERVICES=ccd_gateway,ccd_data,ccd_admin
      - DEFINITION_STORE_HOST=http://ccd-definition-store-api:4451
      - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
      - IDAM_USER_URL=http://idam-api:5000
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - REFORM_SERVICE_NAME=ccd-data-store-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
      - APPINSIGHTS_INSTRUMENTATIONKEY=fake-key
      - CCD_DM_DOMAIN=http://dm-store:4460
      - ELASTIC_SEARCH_ENABLED=${ELASTIC_SEARCH_ENABLED:-false}
      - ELASTIC_SEARCH_HOSTS=ccd-elasticsearch:9200
      - ELASTIC_SEARCH_DATA_NODES_HOSTS=http://ccd-elasticsearch:9200
    ports:
      - 4452:4452

  ccd-user-profile-api:
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - USER_PROFILE_DB_HOST=shared-database
      - USER_PROFILE_DB_PORT=5432
      - USER_PROFILE_DB_USERNAME=ccd_user_profile
      - USER_PROFILE_DB_PASSWORD=ccd_user_profile
      - USER_PROFILE_S2S_AUTHORISED_SERVICES=ccd_data,ccd_definition
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - REFORM_SERVICE_NAME=ccd-user-profile-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
      - APPINSIGHTS_INSTRUMENTATIONKEY=fake-key
      - USER_PROFILE_DB_USE_SSL=false
#    env_file:
#      - env_files/ccd-user-profile-api.env
    ports:
      - 4453:4453

  ccd-case-management-web:
    environment:
      - IDAM_LOGIN_URL=http://localhost:9002/login
      - CCD_GATEWAY_BASE_URL=http://localhost:3453
      - CCD_ACTIVITY_BASE_URL=http://localhost:3455
      - DM_URL=http://localhost:3453/documents
      - DM_URL_REMOTE=http://dm-store:4460/documents
#    env_file:
#      - env_files/ccd-case-management-web.env
    ports:
      - 3451:3451

  ccd-api-gateway:
    environment:
      - IDAM_BASE_URL=http://idam-api:5000
      - IDAM_USER_URL=http://idam-api:5000
      - IDAM_LOGOUT_URL=http://localhost:9002/login/logout
      - IDAM_OAUTH2_TOKEN_ENDPOINT=http://idam-api:5000/oauth2/token
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
      - IDAM_SERVICE_NAME=ccd_gateway
      - IDAM_OAUTH2_CLIENT_SECRET=12345678
      - PROXY_AGGREGATED=http://ccd-data-store-api:4452
      - PROXY_DATA=http://ccd-data-store-api:4452
      - PROXY_DEFINITION_IMPORT=http://ccd-definition-store-api:4451
      - PROXY_DOCUMENT_MANAGEMENT=http://dm-store:4460
#    env_file:
#      - env_files/ccd-api-gateway.env
    ports:
      - 3453:3453

  ccd-logstash:
    ports:
      - 5044:9600

  ccd-elasticsearch:
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
####
  dm-store:
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - SERVER_PORT=4460
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/evidence
      - SPRING_DATASOURCE_USERNAME=evidence
      - SPRING_DATASOURCE_PASSWORD=evidence
      - IDAM_USER_BASE_URI=http://idam-api:5000
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - S2S_NAMES_WHITELIST=ccd_gateway,ccd_data,dg_docassembly_api
      - http_proxy=
      - https_proxy=
      - no_proxy=
      - ROOT_APPENDER=CONSOLE
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=dm-store
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
      - ENABLE_DELETE=true
      - ENABLE_IDAM_HEALTH_CHECK=false
      - ENABLE_METADATA_SEARCH=true
      - ENABLE_DOCUMENT_AND_METADATA_UPLOAD=${ENABLE_DOCUMENT_AND_METADATA_UPLOAD:-false}
      - ENABLE_FOLDER_API=true
      - ENABLE_TTL=true
      - ENABLE_THUMBNAIL=true
      - DM_MULTIPART_WHITELIST=image/jpeg,application/pdf,image/tiff,image/png,image/bmp,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.spreadsheetml.template,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.openxmlformats-officedocument.presentationml.template,application/vnd.openxmlformats-officedocument.presentationml.slideshow
      - DM_MULTIPART_WHITELIST_EXT=.jpg,.jpeg,.bmp,.tif,.tiff,.png,.pdf,.txt,.doc,.dot,.docx,.dotx,.xls,.xlt,.xla,.xlsx,.xltx,.xlsb,.ppt,.pot,.pps,.ppa,.pptx,.potx,.ppsx
      - MAX_FILE_SIZE=500MB
      - MAX_ACTIVE_DB_CONNECTIONS=10
      - ENDPOINTS_HEALTH_SENSITIVE=false
      - ENDPOINTS_INFO_SENSITIVE=false
      - CASE_WORKER_ROLES=caseworker-divorce,caseworker-divorce-courtadmin,caseworker-divorce-solicitor
    ports:
      - 4460:4460


  ccd-user-profile-importer:
    environment:
      - VERBOSE=false
      - MICROSERVICE=ccd_definition
      - CCD_USERS=
      - CCD_JURISDICTIONS=Divorce
      - AUTH_PROVIDER_BASE_URL=http://service-auth-provider-api:8080
      - CCD_USER_PROFILE_URL=http://ccd-user-profile-api:4453
      - CCD_USER_PROFILE_DB_HOST=shared-database
      - CCD_USER_PROFILE_DB_PORT=5432
      - CCD_USER_PROFILE_DB_USERNAME=ccd_user_profile
      - CCD_USER_PROFILE_DB_PASSWORD=ccd_user_profile
      - CCD_USER_PROFILE_DB_DATABASE=ccd_user_profile
      - WAIT_HOSTS=ccd-user-profile-api:4453
      - WAIT_HOSTS_TIMEOUT=900


volumes:
  shared-database-data:
  esdata1:
    driver: local





