---
version: '2.1'

services:
  div-pfe:
    build:
      context: ../div-petitioner-frontend/
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  div-rfe:
    build:
      context: ../div-respondent-frontend/
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  div-dnfe:
    build:
      context: ../div-decree-nisi-frontend/
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  div-dafe:
    build:
      context: ../div-decree-absolute-frontend/
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  redis:
    image: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  fr-am:
    image: hmctsprivate.azurecr.io/idam/idam-fr-am:latest
    hostname: localam
    depends_on:
      shared-db:
        condition: service_started

  fr-idm:
    image: hmctsprivate.azurecr.io/idam/idam-fr-idm:latest
    hostname: localidm
    depends_on:
      fr-am:
        condition: service_started
      shared-db:
        condition: service_started
    mem_limit: 1024m
    memswap_limit: 0

  shared-db:
    image: hmctsprivate.azurecr.io/idam/shared-db:latest
    mem_limit: 512m
    memswap_limit: 0

  smtp-server:
    image: mailhog/mailhog
    mem_limit: 32m
    memswap_limit: 0

  idam-api:
    image: hmctspublic.azurecr.io/idam/api:stable
    depends_on:
      fr-am:
        condition: service_started
      fr-idm:
        condition: service_started
      shared-db:
        condition: service_started

  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:stable
    depends_on:
      idam-api:
        condition: service_started
    mem_limit: 512m
    memswap_limit: 0

  idam-web-admin:
    image: hmctspublic.azurecr.io/idam/web-admin:stable
    depends_on:
      idam-api:
        condition: service_started
    mem_limit: 512m
    memswap_limit: 0

  div-cos:
    build: ../div-case-orchestration-service/
    depends_on:
      div-cms:
        condition: service_started

  div-cms:
    build:
      context: ../div-case-maintenance-service/
    depends_on:
      - service-auth-provider-api

  div-fees-and-payments:
    build:
      context: ../div-fees-and-payments-service/

  div-evidence-management:
    build:
      context: ../div-evidence-management-client-api

  div-payments-api:
    image: hmctspublic.azurecr.io/payment/api
    environment:
      - payments.report.file.location=.
      - PAYMENT_AUDIT_FILE=/tmp/payment-audit.log
      - ASB_CONNECTION_STRING=false
      - FEES_REGISTER_URL=http://fees-api:8080
      - TRUSTED_S2S_SERVICE_NAMES=divorce_frontend,ccd_gateway,bar_api,api_gw
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/payment
      - AUTH_PROVIDER_SERVICE_CLIENT_BASEURL=http://service-auth-provider-api:8080/
      - AUTH_IDAM_CLIENT_BASEURL=http://idam-api:5000/
      - GOV_PAY_URL=https://publicapi.payments.service.gov.uk/v1/payments
      - http_proxy
      - https_proxy
      - no_proxy=idam-api,service-auth-provider-api,$no_proxy
      - MANAGEMENT_SECURITY_DISABLED=false
      - SPRING_DATASOURCE_USERNAME=payment
      - SPRING_DATASOURCE_PASSWORD=payment
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_MAIL_HOST=smtp-server
      - SPRING_MAIL_PORT=1025
      - CCD_CLIENT_URL=http://ccd-data-store-api:4452
      - CORE_CASE_DATA_API_URL=http://ccd-data-store-api:4452
      - CARD_PAYMENTS_REPORT_SCHEDULER_ENABLED=false
      - CARD_PAYMENTS_EMAIL_FROM=no-reply@reform.hmcts.net
      - CARD_PAYMENTS_EMAIL_TO=nowhere@example.com
      - CARD_PAYMENTS_EMAIL_SUBJECT=Local Env:Card Payments Reconciliation Report
      - CARD_PAYMENTS_EMAIL_MESSAGE=Hi <br/><br/>Please find attached today''s reconciliation report. <br/><br/>Regards <br/><br/>Payments team<br/><br/>
      - PBA_DIVORCE_PAYMENTS_REPORT_SCHEDULER_ENABLED=false
      - PBA_DIVORCE_PAYMENTS_EMAIL_FROM=no-reply@reform.hmcts.net
      - PBA_DIVORCE_PAYMENTS_EMAIL_TO=pepito@grillo.com
      - PBA_DIVORCE_PAYMENTS_EMAIL_MESSAGE=hi
      - PBA_DIVORCE_PAYMENTS_EMAIL_SUBJECT=Docker Env Card Payments Reconciliation Report
      - BAR_PAYMENTS_REPORT_SCHEDULER_ENABLED=true
      - BAR_PAYMENTS_EMAIL_FROM=no-reply@reform.hmcts.net
      - BAR_PAYMENTS_EMAIL_TO=pepito@grillo.com
      - BAR_PAYMENTS_EMAIL_MESSAGE=hi
      - BAR_PAYMENTS_EMAIL_SUBJECT=Docker Env Bar Payments Reconciliation Report
      - PBA_PROBATE_PAYMENTS_REPORT_SCHEDULER_ENABLED=false
      - PBA_PROBATE_PAYMENTS_EMAIL_FROM=no-reply@reform.hmcts.net
      - PBA_PROBATE_PAYMENTS_EMAIL_TO=pepito@grillo.com
      - PBA_PROBATE_PAYMENTS_EMAIL_MESSAGE=hi
      - PBA_PROBATE_PAYMENTS_EMAIL_SUBJECT=Docker Env Card Payments Reconciliation Report
      - PBA_FINREM_PAYMENTS_REPORT_SCHEDULER_ENABLED=false
      - PBA_FINREM_PAYMENTS_EMAIL_FROM=no-reply@reform.hmcts.net
      - PBA_FINREM_PAYMENTS_EMAIL_TO=pepito@grillo.com
      - PBA_FINREM_PAYMENTS_EMAIL_MESSAGE=hi
      - PBA_FINREM_PAYMENTS_EMAIL_SUBJECT=Docker Env Card Payments Reconciliation Report
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy
      smtp-server:
        condition: service_started
      service-auth-provider-api:
        condition: service_started

  div-case-data-formatter:
    build:
      context: ../div-case-data-formatter/
    mem_limit: 512m
    memswap_limit: 0

  service-auth-provider-api:
    image: hmctspublic.azurecr.io/rpe/service-auth-provider
    mem_limit: 512m
    memswap_limit: 0

  draft-store-api:
    image: hmctspublic.azurecr.io/draft-store/service:${DRAFT_STORE_API_VERSION:-latest}
    healthcheck:
      retries: 40
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - DRAFT_STORE_DB_HOST=shared-database
      - DRAFT_STORE_DB_PASSWORD=draftstore
      - IDAM_URL=http://idam-api:5000
      - S2S_URL=http://service-auth-provider-api:8080
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy
      service-auth-provider-api:
        condition: service_started

  shared-database:
    image: postgres:9.6-alpine
    command: postgres -c 'max_connections=250'
    volumes:
      - ./docker/database/init-db-v9.6.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: psql -c 'select 1' -d postgres -U postgres
      retries: 40
    mem_limit: 320m
    memswap_limit: 0

  ccd-user-profile-api:
    image: hmctspublic.azurecr.io/ccd/user-profile-api
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy

  ccd-definition-store-api:
    image: hmctspublic.azurecr.io/ccd/definition-store-api
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy

  ccd-data-store-api:
    image: hmctspublic.azurecr.io/ccd/data-store-api
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy

  ccd-case-management-web:
    image: hmctspublic.azurecr.io/ccd/case-management-web
    mem_limit: 256m
    memswap_limit: 0
    depends_on:
      ccd-api-gateway:
        condition: service_started

  ccd-api-gateway:
    image: hmctspublic.azurecr.io/ccd/api-gateway-web
    mem_limit: 256m
    memswap_limit: 0
    depends_on:
      ccd-user-profile-api:
        condition: service_started
      ccd-definition-store-api:
        condition: service_started
      ccd-data-store-api:
        condition: service_started
      service-auth-provider-api:
        condition: service_started

  ###### NOT USED YET
  ccd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - CLUSTER_NAME=ccd-docker-es-cluster
      - DISCOVERY_TYPE=single-node
      - BOOTSTRAP_MEMORY_LOCK=true
      - action.auto_create_index=.security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*
      - JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1

  ccd-logstash:
    image: hmcts/ccd-logstash:latest  # dockerhub - should be changed
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://shared-database:5432/ccd_data_store?stringtype=unspecified&ssl=false
      - DB_USER=ccd_data_store
      - DB_PWD=ccd_data_store
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    depends_on:
      - ccd-elasticsearch
  ###################

  dm-store:
    image: hmcts/dm-store:latest  # dockerhub - should be changed
    command: --wait-for-database 30
    mem_limit: 512m
    memswap_limit: 0

  ccd-user-profile-importer:
    image: hmctspublic.azurecr.io/ccd/user-profile-importer
    mem_limit: 256m
    memswap_limit: 0
    depends_on:
      ccd-user-profile-api:
        condition: service_started

  ccd-importer:
    image: hmctspublic.azurecr.io/cmc/ccd-definition-importer:1.4.2

  idam-importer:
    build:
      context: docker/idam-importer  # local








