---
version: '2.1'

services:
  div-pfe:
    # Image taken from Azure hmctspublic repositories
    image: hmctspublic.azurecr.io/div/pfe:pr-601-d93f08cf
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  div-rfe:
    image: hmctspublic.azurecr.io/div/rfe:pr-375-3d1fd99a
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  div-dnfe:
    image: hmctspublic.azurecr.io/div/dn:pr-416-999c4e87
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  div-dafe:
    image: hmctspublic.azurecr.io/div/da:pr-62-97d006e0
    depends_on:
      - redis
      - div-cos
      - idam-web-public
    mem_limit: 512m
    memswap_limit: 0

  redis:
    image: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  fr-am:
    image: hmctsprivate.azurecr.io/idam/idam-fr-am:latest
    hostname: localam
    depends_on:
      shared-db:
        condition: service_started

  fr-idm:
    image: hmctsprivate.azurecr.io/idam/idam-fr-idm:latest
    hostname: localidm
    depends_on:
      fr-am:
        condition: service_started
      shared-db:
        condition: service_started
    mem_limit: 1024m
    memswap_limit: 0

  shared-db:
    image: hmctsprivate.azurecr.io/idam/shared-db:latest
    mem_limit: 512m
    memswap_limit: 0

  smtp-server:
    image: mailhog/mailhog
    mem_limit: 32m
    memswap_limit: 0

  idam-api:
    image: hmctspublic.azurecr.io/idam/api:latest
    depends_on:
      fr-am:
        condition: service_started
      fr-idm:
        condition: service_started
      shared-db:
        condition: service_started

  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:latest
    depends_on:
      idam-api:
        condition: service_started
    mem_limit: 512m
    memswap_limit: 0

  idam-web-admin:
    image: hmctspublic.azurecr.io/idam/web-admin:latest
    depends_on:
      idam-api:
        condition: service_started
    mem_limit: 512m
    memswap_limit: 0

  div-cos:
    image: hmctspublic.azurecr.io/div/cos:latest
    depends_on:
      div-cms:
        condition: service_started

  div-cms:
    image: hmctspublic.azurecr.io/div/cms:latest
    depends_on:
      - service-auth-provider-api

  service-auth-provider-api:
    image: hmctspublic.azurecr.io/rpe/service-auth-provider
    mem_limit: 512m
    memswap_limit: 0

  shared-database:
    image: postgres:9.6-alpine
    command: postgres -c 'max_connections=250'
    volumes:
      - ./docker/database/init-db-v9.6.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: psql -c 'select 1' -d postgres -U postgres
      retries: 40
    mem_limit: 320m
    memswap_limit: 0

  ccd-user-profile-api:
    image: hmctspublic.azurecr.io/ccd/user-profile-api
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy

  ccd-definition-store-api:
    image: hmctspublic.azurecr.io/ccd/definition-store-api
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy

  ccd-data-store-api:
    image: hmctspublic.azurecr.io/ccd/data-store-api
    mem_limit: 512m
    memswap_limit: 0
    depends_on:
      shared-database:
        condition: service_healthy

  ccd-case-management-web:
    image: hmctspublic.azurecr.io/ccd/case-management-web
    mem_limit: 256m
    memswap_limit: 0
    depends_on:
      ccd-api-gateway:
        condition: service_started

  ccd-api-gateway:
    image: hmctspublic.azurecr.io/ccd/api-gateway-web
    mem_limit: 256m
    memswap_limit: 0
    depends_on:
      ccd-user-profile-api:
        condition: service_started
      ccd-definition-store-api:
        condition: service_started
      ccd-data-store-api:
        condition: service_started
      service-auth-provider-api:
        condition: service_started

###### NOT USED YET
  ccd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - CLUSTER_NAME=ccd-docker-es-cluster
      - DISCOVERY_TYPE=single-node
      - BOOTSTRAP_MEMORY_LOCK=true
      - action.auto_create_index=.security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*
      - JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1

  ccd-logstash:
    image: hmcts/ccd-logstash:latest  # dockerhub - should be changed
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://shared-database:5432/ccd_data_store?stringtype=unspecified&ssl=false
      - DB_USER=ccd_data_store
      - DB_PWD=ccd_data_store
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    depends_on:
      - ccd-elasticsearch
###################

  dm-store:
    image: hmcts/dm-store:latest  # dockerhub - should be changed
    command: --wait-for-database 30
    mem_limit: 512m
    memswap_limit: 0

  ccd-user-profile-importer:
    image: hmctspublic.azurecr.io/ccd/user-profile-importer
    mem_limit: 256m
    memswap_limit: 0
    depends_on:
      ccd-user-profile-api:
        condition: service_started

  idam-importer:
    build:
      context: docker/idam-importer  # local








